import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from 'next/font/google'
import PageTransition from "@/components/PageTransition";
import { AnimatePresence } from "framer-motion";
import TransitionSound from "@/components/TransitionSound";
import CustomCursor from "@/components/CustomCursor";

const inter = Inter({ subsets: ['latin'] })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
   <body>
  <CustomCursor />
  <TransitionSound />

  <AnimatePresence mode="wait">
    <PageTransition>
      {children}
    </PageTransition>
  </AnimatePresence>
</body>
    </html>
  );
}
